name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: gradle
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Bump version
      uses: chkfung/android-version-actions@v1.1
      with:
        gradlePath: app/build.gradle
        versionCode: 5 + ${{github.run_number}}
        
    - name: update version file
      run: |
        sed -i '13s/[0-9]/6/g' app/build.gradle
        git add .
        git commit -m "test"
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: upload APK
      id: uploadArtifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: app
        path: 'app/build/outputs/apk/debug/*.apk'
       
    - name: Add & Commit
  # You may pin to the exact commit or the version.
  # uses: EndBug/add-and-commit@d77762158d703e60c60cf5baa4de52697d1414a3
      uses: EndBug/add-and-commit@v7.4.0
      with:
        add: .
        author_name: dino
        author_email: husky1124@163.com
        branch: master
        message: update version
        github_token: ${{ github.token }}
       
    - name: GitHub Push
  # You may pin to the exact commit or the version.
  # uses: ad-m/github-push-action@40bf560936a8022e68a3c00e7d2abefaf01305a6
      uses: ad-m/github-push-action@v0.6.0
      with:
    # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})
        repository: ltDino/CICDTest
    # Destination branch to push changes
        branch: master
    # Directory to change to before pushing.
        directory: .
       
    - name: Cleanup Gradle Cache
    # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
    # Restoring these files from a GitHub Actions cache might cause problems for future builds.
      run: |
        rm -f ~/.gradle/caches/modules-2/modules-2.lock
        rm -f ~/.gradle/caches/modules-2/gc.properties
